version: '3.8'

services:
  database:
    container_name: diplomarbeit
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: diplomarbeit
      MYSQL_USER: diplomarbeit
      MYSQL_PASSWORD: diplomarbeit
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
  node:
    container_name: backend_express_test
    image: backend_firewall
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: diplomarbeit
      DB_PASSWORD: diplomarbeit
      DB_DATABASE: diplomarbeit
      SSL_CERT_PATH: /app/sslCertificate/certificate.crt
      SSL_KEY_PATH: /app/sslCertificate/private.key
      API_TOKEN: vSlnYxXbaiVQxkE6yVl62ZSiJN1gjRu2
      PORT: 3000
      MANAGEMENT_IP: https://192.168.200.200:8443
      ACCESS_TOKEN_SECRET: e798941e5d4aa9b247099ca80d064057d8bc2c6b0f00eca6ff2251c466581bc56e789c1f0927be18b2f5bfa2d711c087219489d9b2bca7d3fb0704f983c59461
      REFRESH_TOKEN_SECRET: 0a2c15728ee9c3dc82678b09663ae9f3f1ec1caa3d3b4b7d2b8a25b11e91ce7b572152bd8ee0665125f65d1507667af9baede52240ab2026a2b09e9c2f112fbd
    ports:
      - '3000:3000'
    links:
      - database
    volumes:
      - ./sslCertificate:/app/sslCertificate