name: Docker Build

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub (Optional)
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Docker Image
        if: success()
        run: |
          docker build -t constiriedler/backend_firewall:latest .
          docker push constiriedler/backend_firewall:latest
