name: Docker Image CI

on:
  push:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag firewall_backend:latest

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag the Docker image with the version
      run: docker tag firewall_backend:latest constiriedler/firewall_backend:1.3

    - name: Tag the Docker image with latest
      run: docker tag firewall_backend:latest constiriedler/firewall_backend:latest

    - name: Push the versioned Docker image to Docker Hub
      run: docker push constiriedler/firewall_backend:1.3

    - name: Push the latest Docker image to Docker Hub
      run: docker push constiriedler/firewall_backend:latest
